### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj-chart#1]
Just had a short look over the project.

Overall it follows the same structure we have for the other AsciidoctorJ extension projects, nice!

A few things that I noticed:

- The integration test module seems to have the test outputs in the src folder, that should probably not be the case.
- The file publish.gradle seems to be directly copied from asciidoctorj-diagram, please change the URLs pointing to the correct repo, and please add your own name to pom.developers. I guess it's fine to remove all of the current developers in this list (Dan, Alex & me) since we did not really contribute to this project yet, so all the praise should be for you!
- It would be great to see this project go to the Gradle 7.x and Java 16 since Java 17 is already close. I also updated asciidoctorj-diagram recently to the latest versions.
- If I am not missing anything the definition of the "providedConfiguration" seems to be unused. Maybe best to remove it in that case.

**Comment by uniqueck** [comment]
Hi @robertpanzer,
thx for review this extension wrapper. 

> * The integration test module seems to have the test outputs in the src folder, that should probably not be the case.

If you mean the files line-chart.adoc and line-chart.html, the second one is the expected output if line-chart.adoc is process with the chart extension. The test outputs are written to an temporary directory, this is done via @TempDir JUnit5 extension mechanism and asciidoctorj options for output directory.

> * The file publish.gradle seems to be directly copied from asciidoctorj-diagram, please change the URLs pointing to the correct repo, and please add your own name to pom.developers. I guess it's fine to remove all of the current developers in this list (Dan, Alex & me) since we did not really contribute to this project yet, so all the praise should be for you!

You are so right, this is fixed.

> * It would be great to see this project go to the Gradle 7.x and Java 16 since Java 17 is already close. I also updated asciidoctorj-diagram recently to the latest versions.

This is done.

> * If I am not missing anything the definition of the "providedConfiguration" seems to be unused. Maybe best to remove it in that case.

This is done.

**Comment by uniqueck** [comment]
Hi @robertpanzer,

I would like to implement the release process via tag and GitHub Actions. Is that ok for you?

**Comment by robertpanzer** [comment]
Yes, of course. For this repo this is fine.

**Comment by uniqueck** [comment]
@robertpanzer how do you start an release locally?
I think about to call gradle build -Pversion=version extracted from tag name
gradle publish -PpublishRelease=true?
What is with the both gradle files publish and sigining? They are not used currently. How do you activate them?

**Comment by uniqueck** [comment]
Hi @robertpanzer,

i created a first version for the release process via github actions via git tag pushed manually.
The credentials and pgp key for the signing part, where can i get this? I think this have to be for org.asciidoctor another one as for my personal stuff. Should Dan add me one Sonatype JIRA to asciidoctor team?

Final questing is everythin fine to move this repository to the asciidoctor organization?

**Comment by robertpanzer** [comment]
Yes, iirc @mojavelinux would need to request the permission for you to publish to the org.asciidoctor group.
I can't remember that I would have published my pgp key at sonatype, but I just published it to some other public key server.
@mojavelinux would also need to transfer the repo into the Asciidoctor org once he is fine with it and give you the necessary rights for it.
In its current form I am fine with publishing the extension under the asciidoctor org.

**Comment by uniqueck** [comment]
@mojavelinux is that ok for you?

**Comment by mojavelinux** [comment]
I'm on vacation at the moment. I can follow up later in the week.

**Comment by uniqueck** [comment]
Hi @mojavelinux, if you have time my user at sonatype jira is `uniqueck-jira`, so you can add me to the organization asciidoctor.

**Comment by mojavelinux** [comment]
I will follow-up this weekend.

**Comment by uniqueck** [comment]
If you need something from me let me know.

**Comment by mojavelinux** [comment]
Let's start by transferring the repository since we don't want to release into org.asciidoctor out of a non-Asciidoctor repository.

**Comment by mojavelinux** [comment]
@uniqueck You should be able to transfer the repository to the asciidoctor organization now. Once you are done, let me know so I can update the permissions.

**Comment by mojavelinux** [comment]
I'm currently locked of my Sonatype OSS account, so I can't request access to the org.asciidoctor group ID until that is resolved. I have requested for my account to be restored.

**Comment by mojavelinux** [comment]
Okay, I managed to file the issue to request access to the org.asciidoctor groupId. https://issues.sonatype.org/browse/OSSRH-73142 I don't think it's necessary to declare the new project / artifactId.

**Comment by uniqueck** [comment]
@mojavelinux it doesn't work. I'm not allowed to create public repositories in asciidoctor organization, so i'm not able to move this repository.

**Comment by mojavelinux** [comment]
Let me try the other setting (GitHub is constantly changing how this works, so it's always trial and error). Please try again.

**Comment by uniqueck** [comment]
Ok it looks good, i have to choose groups who have access to that repository. Which one should i choose? asciidoctor-chart?

**Comment by uniqueck** [comment]
Ok it is done, do you need to adjust the permissions?

**Comment by mojavelinux** [comment]
I will adjust the group and permissions. This is typical for a transfer.

**Comment by mojavelinux** [comment]
I've updated the permissions. The repository is classified under the group asciidoctorj, and I have added you as an admin on the repository as well.

What's next?

**Comment by uniqueck** [comment]
I check everything define the necessary secrets and prepare the first release. Announcement goes to zulip.

**Comment by mojavelinux** [comment]
Great! If you need anything, just let me know. I'll try respond as quickly as possible.

**Comment by uniqueck** [comment]
@mojavelinux @robertpanzer  is it possible in sonatype nexus oss to see the staging repositories via ui for org.asciidoctor? I try to publish and close the repository via gradle tasks, but it fails on closing this repository. I have to check via nexus ui why.

**Comment by robertpanzer** [comment]
Yes, you can login to oss.sonatype.org. 
There should be a menu item for staging repositories.

**Comment by uniqueck** [comment]
Hi @robertpanzer yes this works for doctoolchain and for my own groupId but org.asciidoctor is not there.

**Comment by uniqueck** [comment]
Ah i found the difference. For org.asciidoctor we use the legacy host oss.sonatype.org and on my side i use the s01.oss.sonatype.org host. Since april this year you have to use s01.oss.sonatype.org.
